version: 1

sources:
  - name: raw_data
    database: data_warehouse  
    schema: raw_data          
    tables:
      - name: account
      - name: lecture_application_students
      - name: lecture_change_form
      - name: lecture_teacher_vt
      - name: lecture_tutor
      - name: lecture_video_tutoring
      - name: lecture_vt_schedules
      - name: payment
      - name: school
      - name: school_university
      - name: seoltab_teacher_config
      - name: student
      - name: student_change_pause_history
      - name: student_change_subject_v2
      - name: teacher
      - name: term_taxonomy_name
      - name: tteok_ham
      - name: user   