dbt_dev: # this needs to match the profile in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: postgres
      host: "data-warehouse-dev.cgoj9fqfqdng.ap-northeast-2.rds.amazonaws.com"
      user: "DS_Master"
      password: "Goodonuii1!"
      port: 5432
      dbname: "data_warehouse" 
      #schema: "public"
      threads: 1


      